name: myapp

services:
  keycloak:
    image: keycloak/keycloak:26.6
    container_name: keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}

  rabbitmq-broker:
    container_name: rabbitmq-broker
    image: rabbitmq:4.3.0-management
    ports: 
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGE_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 40s

  permission-postgres:
    image: postgres:18.4
    container_name: permission-postgres
    ports: 
      - ${PERMISSION_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${PERMISSION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PERMISSION_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PERMISSION_POSTGRES_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${PERMISSION_POSTGRES_NAME} -U ${PERMISSION_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  permission-migrations:
    container_name: permission-migrations
    depends_on:
      permission-postgres:
        condition: service_healthy
    build: ./permission-service
    environment:
      POSTGRES_USER: ${PERMISSION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PERMISSION_POSTGRES_PASSWORD}
      POSTGRES_HOST: permission-postgres
      POSTGRES_PORT: 5432
      POSTGRES_NAME: ${PERMISSION_POSTGRES_NAME}
    entrypoint: ["bash", "/app/run_migrations.sh"]
    volumes:
      - ./.alembic/permission/:/app/alembic/versions

  permission-service:
    container_name: permission-service
    depends_on:
      auth-service:
        condition: service_started
      permission-migrations:
        condition: service_completed_successfully
      rabbitmq-broker:
        condition: service_healthy
    build: ./permission-service
    ports:
      - ${PERMISSION_BACKEND_PORT}:8000
    environment:
      POSTGRES_USER: ${PERMISSION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PERMISSION_POSTGRES_PASSWORD}
      POSTGRES_HOST: permission-postgres
      POSTGRES_PORT: 5432
      POSTGRES_NAME: ${PERMISSION_POSTGRES_NAME}

      BACKEND_WORKERS: ${PERMISSION_BACKEND_WORKERS}
      BACKEND_ADMIN_GROUP_NAME: ${BACKEND_ADMIN_GROUP_NAME}

      AUTH_HOST: keycloak
      AUTH_PORT: 8000
      AUTH_API_PATH: ${AUTH_API_PATH}

      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: rabbitmq-broker
      RABBITMQ_PORT: 5672

  checker-service:
    container_name: checker-service
    depends_on:
      permission-service:
        condition: service_started
    build: ./checker-service
    ports:
      - ${CHECKER_BACKEND_PORT}:8000
    environment:
      BACKEND_WORKERS: ${CHECKER_BACKEND_WORKERS}
      BACKEND_ADMIN_GROUP_NAME: ${BACKEND_ADMIN_GROUP_NAME}

      AUTH_HOST: keycloak
      AUTH_PORT: 8000
      AUTH_API_PATH: ${AUTH_API_PATH}

      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: rabbitmq-broker
      RABBITMQ_PORT: 5672